// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.iancodes.collegesailors.model;

import com.iancodes.collegesailors.model.FleetScore;

privileged aspect FleetScore_Roo_JavaBean {
    
    public int FleetScore.getPlace() {
        return this.place;
    }
    
    public void FleetScore.setPlace(int place) {
        this.place = place;
    }
    
}
