// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.iancodes.collegesailors.model;

import com.iancodes.collegesailors.model.Fleet;

privileged aspect Fleet_Roo_JavaBean {
    
    public String Fleet.getFleetName() {
        return this.fleetName;
    }
    
    public void Fleet.setFleetName(String fleetName) {
        this.fleetName = fleetName;
    }
    
}
